### ISSUE TITLE
Sample apk

### ISSUE THREAD

**Issue by wasdennnoch** [eoinfogarty/Onboarding#4]
Hi, could you please add a link to download the sample app as an apk, I currently can't compile the project myself and it would help everyone seeing the library to have a working example to see how awesome it is :D

**Comment by Dwite** [comment]
@wasdennnoch here is link https://dl.dropboxusercontent.com/u/31880748/onboarding-sample.apk build from Master branch on 16.08.16

**Comment by eoinfogarty** [comment]
@Dwite Thanks for that, I've added the link to the README.

Ill close this issue now
